### ISSUE TITLE
Failed to load shaderpack

### ISSUE THREAD

**Issue by Ein420** [sixthsurge/photon#133]
### What happened?

Updated to  https://github.com/sixthsurge/photon/commit/08bf5a01c1d83e7793ab71c054fca6942c35e069 
saw another issue related to colored lights, mine doesn't work regardless of whether the colored lights setting is on or off
also doesn't work with or without the distant horizens mod
using this on 1.20.4, which it has worked on previously to updating the shader

### Minecraft Version

1.20.2

### Which shader mod are you using?

Iris

### Shader mod version

1.7.0 

### Shader settings

```conf
#Mon Apr 08 20:19:52 WAT 2024
STARS_COVERAGE=0.55
shadowDistance=256.0
SKYLIGHT_I=1.02
WATER_WAVE_ITERATIONS=3
DIRECTIONAL_LIGHTMAPS_INTENSITY=0.35
AIR_FOG_MIE_DENSITY_EVENING=0.0023
CLOUDS_CUMULUS_WIND_SPEED=11.0
SPECULAR_MAPPING=true
WEATHER_D0_CLOUDS_STRATUS_AMOUNT=0.24
VANILLA_SUN=true
GRADE_SATURATION=1.03
CLOUDS_CIRRUS_WIND_SPEED=30.0
tonemap_right=tonemap_hejl_burgess
POM_SHADOW=true
POM_SHADOW_SAMPLES=30
tonemap_left=tonemap_hejl_burgess
AUTO_EXPOSURE=AUTO_EXPOSURE_SIMPLE
BLOOM_INTENSITY=1.22
BLOCK_ENTITY_SHADOWS=true
NORMAL_MAPPING=true
SSR_ROUGHNESS_SUPPORT=false
VL_RENDER_SCALE=0.96
DOF_INTENSITY=0.60
EDGE_HIGHLIGHT=true
CAS_INTENSITY=1.00
POM=true
CLOUDS_CUMULUS_LIGHTING_STEPS=8
BLOCKY_CLOUDS_LAYER_2=true
CLOUDS_CUMULUS_AMBIENT_STEPS=3
CLOUDS_ALTOCUMULUS_WIND_SPEED=11.0
AIR_FOG_MIE_DENSITY_MORNING=0.0043
AIR_FOG_MIE_DENSITY_RAIN=0.027
TAAU=true
SSR_RAY_COUNT=5
SNELLS_WINDOW=true
POM_DEPTH=0.30
TAAU_RENDER_SCALE=1.00
CAVE_LIGHTING_I=1.49
WATER_CAUSTICS=true
tonemap=academy_rrt
WATER_ABSORPTION_G_UNDERWATER=0.07
AIR_FOG_MIE_DENSITY_BLUE_HOUR=0.0017
SKY_GROUND=true
POM_SAMPLES=35
SSR_REFINEMENT_STEPS=5
AIR_FOG_MIE_DENSITY_MIDNIGHT=0.0040
SH_SKYLIGHT=true
DOF_SAMPLES=50
WATER_ABSORPTION_B=0.08
HANDHELD_LIGHTING_INTENSITY=1.01
BLOOMY_FOG_INTENSITY=0.9
AIR_FOG_COLORED_LIGHT_SHAFTS=true
AIR_FOG_MIE_DENSITY_NOON=0.0005
EMISSION_STRENGTH=0.25
WATER_FOAM=true
WATER_SCATTERING=0.03
SHADING_STRENGTH=1.01
DIRECTIONAL_LIGHTMAPS=true
WEATHER_D0_FOGGINESS=0.38
GTAO=false
SHADOW_PENUMBRA_SCALE=0.9
GRADE_BRIGHTNESS=0.99
```

### Relevant log output

```text
latest.log

[20:19:52] [Render thread/INFO]: Using shaderpack: photon.zip
[20:19:52] [Render thread/INFO]: Creating pipeline for dimension NamespacedId{namespace='minecraft', name='overworld'}
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/WARN]: Ignoring ConstDirective { INT voxelDistance = 32; } because it is of the wrong type, a type of float is expected.
[20:19:53] [Render thread/INFO]: Starting custom uniform resolving
[20:19:54] [Render thread/WARN]: Type is VERTEX
[20:19:54] [Render thread/WARN]: Type is FRAGMENT
[20:19:54] [Render thread/WARN]: Couldn't find worldYOffset
[20:19:54] [Render thread/WARN]: Couldn't find iris_ProjectionMatrix
[20:19:54] [Render thread/WARN]: Couldn't find iris_ProjectionMatrixInverse
[20:19:54] [Render thread/WARN]: Couldn't find iris_ModelViewMatrixInverse
[20:19:54] [Render thread/WARN]: Couldn't find iris_NormalMatrix
[20:19:54] [Render thread/WARN]: Couldn't find clipDistance
[20:19:54] [Render thread/WARN]: Type is VERTEX
[20:19:54] [Render thread/WARN]: Type is FRAGMENT
[20:19:54] [Render thread/WARN]: Couldn't find worldYOffset
[20:19:54] [Render thread/WARN]: Couldn't find iris_ProjectionMatrix
[20:19:54] [Render thread/WARN]: Couldn't find iris_ProjectionMatrixInverse
[20:19:54] [Render thread/WARN]: Couldn't find iris_ModelViewMatrixInverse
[20:19:54] [Render thread/WARN]: Couldn't find iris_NormalMatrix
[20:19:54] [Render thread/WARN]: Couldn't find clipDistance
[20:19:55] [Render thread/WARN]: The in declaration 'atlas_tile_scale' in the FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[20:19:55] [Render thread/WARN]: The in declaration 'atlas_tile_coord' in the FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[20:19:55] [Render thread/WARN]: The in declaration 'atlas_tile_offset' in the FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[20:19:55] [Render thread/WARN]: The in declaration 'tangent_pos' in the FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[20:19:55] [Render thread/WARN]: The in declaration 'atlas_tile_offset' in the FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[20:19:55] [Render thread/WARN]: The in declaration 'atlas_tile_scale' in the FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[20:19:55] [Render thread/WARN]: The in declaration 'tangent_pos' in the FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[20:19:55] [Render thread/WARN]: The in declaration 'atlas_tile_coord' in the FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[20:19:55] [Render thread/INFO]: [System] [CHAT] The shaderpack failed to load! Please report the error to the shader developer. Copy Info
[20:19:55] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
net.irisshaders.iris.gl.shader.ShaderCompileException: entities_alpha.fsh: entities_alpha.fsh: 0:188(1): error: `return' with wrong type int, in function `fix_material_mask' returning uint
0:192(1): error: `return' with wrong type int, in function `fix_material_mask' returning uint

	at net.minecraft.class_281.handler$cpm000$iris$causeException(class_281.java:536) ~[client-intermediary.jar:?]
	at net.minecraft.class_281.method_34416(class_281.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_281.method_1283(class_281.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.method_34579(class_5944.java:242) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:186) ~[client-intermediary.jar:?]
	at net.irisshaders.iris.pipeline.programs.ExtendedShader.<init>(ExtendedShader.java:81) ~[iris-1.7.0-snapshot+mc1.20.4-dfec34d-dirty.jar:?]
	at net.irisshaders.iris.pipeline.programs.ShaderCreator.create(ShaderCreator.java:110) ~[iris-1.7.0-snapshot+mc1.20.4-dfec34d-dirty.jar:?]
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.createShader(IrisRenderingPipeline.java:697) ~[iris-1.7.0-snapshot+mc1.20.4-dfec34d-dirty.jar:?]
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.createShader(IrisRenderingPipeline.java:674) ~[iris-1.7.0-snapshot+mc1.20.4-dfec34d-dirty.jar:?]
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.lambda$new$12(IrisRenderingPipeline.java:420) ~[iris-1.7.0-snapshot+mc1.20.4-dfec34d-dirty.jar:?]
	at net.irisshaders.iris.pipeline.programs.ShaderMap.<init>(ShaderMap.java:21) ~[iris-1.7.0-snapshot+mc1.20.4-dfec34d-dirty.jar:?]
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.<init>(IrisRenderingPipeline.java:411) ~[iris-1.7.0-snapshot+mc1.20.4-dfec34d-dirty.jar:?]
	at net.irisshaders.iris.Iris.createPipeline(Iris.java:586) ~[iris-1.7.0-snapshot+mc1.20.4-dfec34d-dirty.jar:?]
	at net.irisshaders.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:33) ~[iris-1.7.0-snapshot+mc1.20.4-dfec34d-dirty.jar:?]
	at net.irisshaders.iris.Iris.reload(Iris.java:530) ~[iris-1.7.0-snapshot+mc1.20.4-dfec34d-dirty.jar:?]
	at net.irisshaders.iris.apiimpl.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:28) ~[iris-1.7.0-snapshot+mc1.20.4-dfec34d-dirty.jar:?]
	at net.irisshaders.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:579) ~[iris-1.7.0-snapshot+mc1.20.4-dfec34d-dirty.jar:?]
	at net.irisshaders.iris.gui.screen.ShaderPackScreen.lambda$init$3(ShaderPackScreen.java:238) ~[iris-1.7.0-snapshot+mc1.20.4-dfec34d-dirty.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:95) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.irisshaders.iris.gui.screen.ShaderPackScreen.method_25402(ShaderPackScreen.java:187) ~[iris-1.7.0-snapshot+mc1.20.4-dfec34d-dirty.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:180) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:180) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509) ~[lwjgl-glfw-3.3.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1352) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[fabric-loader-0.15.9-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.9.jar:?]
[20:19:55] [Render thread/INFO]: Stopping worker threads
[20:19:55] [Render thread/INFO]: Started 3 worker threads
```

**Comment by sixthsurge** [comment]
will fix

**Comment by sixthsurge** [comment]
should be fixed in latest commit
