### ISSUE TITLE
Failed to create shader rendering pipeline, disabling shaders!

### ISSUE THREAD

**Issue by AStrong34** [sixthsurge/photon#167]
### What happened?

Every time I try to enable these shaders, I get an error and it rollsback to disabling my shaders. I cannot get Photon shaders to work whatsoever. 

In the log file it says "Shaders are disabled because enableShaders is set to false in iris.properties" even though it is clearly enabled as I can use all other shaders

### Minecraft Version

1.19

### Which shader mod are you using?

Iris

### Shader mod version

verison 1.0

### Shader settings

```conf
It auto defaults to "Custom" even when I set it to low or medium.
```

### Relevant log output

```text
[17:15:30] [Render thread/INFO]: Destroying pipeline OVERWORLD
[17:15:30] [Render thread/INFO]: Shaders are disabled because enableShaders is set to false in iris.properties
[17:15:30] [Render thread/INFO]: Shaders are disabled
[17:15:30] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[17:15:30] [Render thread/INFO]: Stopping worker threads
[17:15:30] [Render thread/INFO]: Started 6 worker threads
[17:15:30] [Render thread/INFO]: [CHAT] Shaders disabled!
[17:15:31] [Render thread/INFO]: [STDOUT]: Player queue for update: 1
[17:15:31] [Render thread/INFO]: Destroying pipeline OVERWORLD
[17:15:31] [Render thread/WARN]: Unexpected value for boolean key shadow.culling in shaders.properties: got reversed, but expected either true or false
[17:15:31] [Render thread/WARN]: Per-buffer pass blending directives are not supported, ignoring blend directive for blend.gbuffers_armor_glint.colortex0
[17:15:31] [Render thread/WARN]: Per-buffer pass blending directives are not supported, ignoring blend directive for blend.gbuffers_basic.colortex0
[17:15:31] [Render thread/WARN]: Per-buffer pass blending directives are not supported, ignoring blend directive for blend.dh_water.colortex0
[17:15:31] [Render thread/WARN]: Per-buffer pass blending directives are not supported, ignoring blend directive for blend.gbuffers_water.colortex0
[17:15:31] [Render thread/WARN]: Per-buffer pass blending directives are not supported, ignoring blend directive for blend.gbuffers_weather.colortex0
[17:15:31] [Render thread/WARN]: Per-buffer pass blending directives are not supported, ignoring blend directive for blend.gbuffers_hand_water.colortex0
[17:15:31] [Render thread/WARN]: Per-buffer pass blending directives are not supported, ignoring blend directive for blend.gbuffers_textured.colortex0
[17:15:31] [Render thread/WARN]: Per-buffer pass blending directives are not supported, ignoring blend directive for blend.gbuffers_entities_translucent.colortex0
[17:15:31] [Render thread/WARN]: Per-buffer pass blending directives are not supported, ignoring blend directive for blend.gbuffers_block_translucent.colortex0
[17:15:31] [Render thread/WARN]: Per-buffer pass blending directives are not supported, ignoring blend directive for blend.gbuffers_particles_translucent.colortex0
[17:15:31] [Render thread/WARN]: Custom texture directive for stage deferred, sampler depthtex0 contains more parts than we expected: image/atmosphere/scattering.dat TEXTURE_3D RGB16F 32 64 32 RGB HALF_FLOAT
[17:15:31] [Render thread/WARN]: Custom texture directive for stage deferred, sampler colortex6.1 contains more parts than we expected: image/worley_noise.dat TEXTURE_3D R8 64 64 64 RED UNSIGNED_BYTE
[17:15:31] [Render thread/WARN]: Custom texture directive for stage deferred, sampler colortex7.1 contains more parts than we expected: image/curl_noise.dat TEXTURE_3D RGB8 32 32 32 RGB UNSIGNED_BYTE
[17:15:31] [Render thread/WARN]: Custom texture directive for stage composite, sampler colortex0 contains more parts than we expected: image/worley_noise.dat TEXTURE_3D R8 64 64 64 RED UNSIGNED_BYTE
[17:15:31] [Render thread/WARN]: Unable to resolve shader pack option menu element "LIGHTNING_FLASH" defined in shaders.properties
[17:15:31] [Render thread/WARN]: Unable to resolve shader pack option menu element "CLOUDS_CUMULUS_CONGESTUS_PRIMARY_STEPS_H" defined in shaders.properties
[17:15:31] [Render thread/WARN]: Unable to resolve shader pack option menu element "CLOUDS_CUMULUS_CONGESTUS_PRIMARY_STEPS_Z" defined in shaders.properties
[17:15:31] [Render thread/WARN]: Unable to resolve shader pack option menu element "NOISE_ON_DH_TERRAIN" defined in shaders.properties
[17:15:31] [Render thread/INFO]: Profile: Custom (+15 options changed by user)
[17:15:32] [Render thread/INFO]: null:1069:2: error: #error "This program should be disabled if Motion Blur is disabled"
[17:15:32] [Render thread/INFO]: null:1069:2: error: #error "This program should be disabled if Motion Blur is disabled"
[17:15:32] [Render thread/INFO]: null:1069:2: error: #error "This program should be disabled if Motion Blur is disabled"
[17:15:32] [Render thread/INFO]: null:1069:2: error: #error "This program should be disabled if Motion Blur is disabled"
[17:15:32] [Render thread/INFO]: null:1069:2: error: #error "This program should be disabled if Motion Blur is disabled"
[17:15:32] [Render thread/INFO]: null:1069:2: error: #error "This program should be disabled if Motion Blur is disabled"
[17:15:32] [Render thread/INFO]: Using shaderpack: photon_v1.0a (1).zip
[17:15:32] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[17:15:32] [Render thread/WARN]: Shader compilation log for prepare.fsh: ERROR: 0:841: 'location' : overlapping use of location 0
ERROR: 1 compilation errors.  No code generated.


[17:15:32] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: Shader compilation failed!
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:236) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:94) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:207) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:642) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) [iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.Iris.reload(Iris.java:584) [iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.Iris.toggleShaders(Iris.java:257) [iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.Iris.handleKeybinds(Iris.java:238) [iris-mc1.19-1.2.5.jar:?]
	at net.minecraft.class_310.handler$dgf003$iris$onTick(class_310.java:18377) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1869) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1101) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.14.25.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.25.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.25.jar:?]
Caused by: java.lang.RuntimeException: Failed to compile FRAGMENT shader for program prepare.fsh
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:78) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:232) ~[iris-mc1.19-1.2.5.jar:?]
	... 15 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:40) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:21) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:76) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:232) ~[iris-mc1.19-1.2.5.jar:?]
	... 15 more
[17:15:32] [Render thread/INFO]: Stopping worker threads
[17:15:32] [Render thread/INFO]: Started 6 worker threads
[17:15:32] [Render thread/INFO]: [CHAT] Toggled shaders to (off) [fallback, check your logs for details]!
```

**Comment by OKHI233** [comment]
Unless I have some misunderstanding with the log you posted, your Iris version is ancient, which does not support all the features that Photon needs. Please upgrade to the latest version (1.6.11 for 1.19-1.19.2) and see if it's still an issue.

**Comment by AStrong34** [comment]
![Minecraft_ 1 19 - Multiplayer (3rd-party Server) 5_27_2024 5_49_42 PM](https://github.com/sixthsurge/photon/assets/95600764/63984340-9e8e-49ed-af2e-a588d3968697)
upon updating Iris, this is how the shaderpack looks.. No matter if I have any resource packs installed or not.
