### ISSUE TITLE
Colored lights crash the game

### ISSUE THREAD

**Issue by HenryLongHead** [sixthsurge/photon#185]
### What happened?

Colored lights crash the game as soon as it loads. Can't even join a world or change the settings. Tried on many versions such as 1.20.2, 1.20.4 and 1.21. It used to work but doesn't anymore, God knows why. Fedora Linux 40, prism launcher (flatpak), rx 7700 xt.

### Minecraft Version

1.20.2

### Which shader mod are you using?

Iris

### Shader mod version

1.7.1+mc1.20.4

### Shader settings

```conf
COLORED_LIGHTS=true
```

**Comment by Meepster-836** [comment]
This also crashes the game for me if I have colored lights on. I'm on Pop!OS 22.04, using the prism launcher flatpak, and an RX 6700 XT. I've got a log file if that helps.
[log.txt](https://github.com/user-attachments/files/15935125/log.txt)

**Comment by fnky** [comment]
Same here. On Apple M1 Pro (macOS Sonoma 14.3.1) with Metal (I assume it uses OpenGL 4.1 since it reports as "4.1 Metal - 88" in the F3 stats)

Though it doesn't crash the game, just Iris. This is the stacktrace I got from enabling debug setting in Iris and enabling Colored Lights in photon:

```
java.lang.NullPointerException
	at org.lwjgl.system.Checks.check(Checks.java:188)
	at org.lwjgl.opengl.GL44C.glClearTexImage(GL44C.java:1126)
	at org.lwjgl.opengl.ARBClearTexture.glClearTexImage(ARBClearTexture.java:331)
	at net.irisshaders.iris.gl.image.GlImage.setup(GlImage.java:69)
	at net.irisshaders.iris.gl.image.GlImage.<init>(GlImage.java:45)
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.<init>(IrisRenderingPipeline.java:233)
	at net.irisshaders.iris.Iris.createPipeline(Iris.java:578)
	at net.irisshaders.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:33)
	at net.irisshaders.iris.Iris.reload(Iris.java:529)
	at net.irisshaders.iris.apiimpl.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:28)
	at net.irisshaders.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:627)
	at net.irisshaders.iris.gui.screen.ShaderPackScreen.lambda$init$6(ShaderPackScreen.java:265)
	at net.minecraft.class_4185.method_25306(class_4185.java:96)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:141)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.irisshaders.iris.gui.screen.ShaderPackScreen.method_25402(ShaderPackScreen.java:226)
	at net.minecraft.class_312.method_1611(class_312.java:101)
	at net.minecraft.class_437.method_25412(class_437.java:467)
	at net.minecraft.class_312.method_1601(class_312.java:101)
	at net.minecraft.class_312.method_22686(class_312.java:186)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:186)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:200)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:218)
	at net.minecraft.class_1041.method_15998(class_1041.java:287)
	at net.minecraft.class_310.method_1523(class_310.java:1342)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by VHSJayden** [comment]
Same here. I wonder if this is a shader issue or a Linux issue?

**Comment by slayer3032** [comment]
I am experiencing this with Mesa versions 24.1 and newer.

**Comment by Darogirn** [comment]
It's the same here for me. Has anybody found a solution apart from rolling back the Mesa version?

**Comment by slayer3032** [comment]
> It's the same here for me. Has anybody found a solution apart from rolling back the Mesa version?

Haven't found any yet aside from turning off color lights, it was mentioned in the Iris discord and one of the developers has reported it to Mesa. https://gitlab.freedesktop.org/mesa/mesa/-/issues/11980

**Comment by slayer3032** [comment]
Should be working again in Mesa 24.2.5 and latest 24.3 git!
