### ISSUE TITLE
No outline when paired with OptiFine

### ISSUE THREAD

**Issue by OKHI233** [sixthsurge/photon#84]
### What happened?

It seems like there's no outline (both block selection and the "show entity hitboxes" debug function) when using Photon with OptiFine. However, other shaders worked fine. I'm using Ultra profile with Colored Lights turned off. 
![Minecraft NeoForge_ 1 20 1 - Singleplayer 2023_11_21 21_30_11](https://github.com/sixthsurge/photon/assets/43093801/0f4d8955-abec-4aac-aa3e-e03a9e579b92)
![Minecraft NeoForge_ 1 20 1 - Singleplayer 2023_11_21 21_30_02](https://github.com/sixthsurge/photon/assets/43093801/ad3dd95d-96a3-4ad6-91cb-3c8ddf67f342)
It's also not the case for Sodium+Iris. 
![Minecraft_ 1 20 1 2023_11_21 21_33_56](https://github.com/sixthsurge/photon/assets/43093801/70f6af4b-b01b-4b89-b686-806904884e65)
![Minecraft_ 1 20 1 2023_11_21 21_34_03](https://github.com/sixthsurge/photon/assets/43093801/ea52f6a0-b4ac-4e30-a043-756a1c2307b4)

Edit: added the log, updated settings and OptiFine version. 

### Minecraft Version

1.20.1

### Which shader mod are you using?

Optifine

### Shader mod version

OptiFine HD U I6

### Shader settings

```conf
#Mon Jan 08 19:24:34 HKT 2024
shadowMapResolution=4096
SPECULAR_MAPPING=true
BLOCK_ENTITY_SHADOWS=true
NORMAL_MAPPING=true
INFO=3
WATER_CAUSTICS=true
AIR_FOG_COLORED_LIGHT_SHAFTS=true
```

### Relevant log output

```conf
[141月2024 04:55:16.162] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] Invalid program name: gbuffers_particles
[141月2024 04:55:16.162] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] Invalid program name: gbuffers_block_translucent
[141月2024 04:55:16.162] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] Invalid program name: gbuffers_entities_translucent
[141月2024 04:55:16.163] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] Invalid program name: gbuffers_particles_translucent
[141月2024 04:55:16.163] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] Invalid program name: gbuffers_particles
[141月2024 04:55:16.163] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] Invalid program name: gbuffers_block_translucent
[141月2024 04:55:16.163] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] Invalid program name: gbuffers_entities_translucent
[141月2024 04:55:16.163] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] Invalid program name: gbuffers_particles_translucent
[141月2024 04:55:16.164] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Blend gbuffers_armor_glint.colortex0=ONE ONE ONE ZERO
[141月2024 04:55:16.164] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Blend gbuffers_basic.colortex0=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ZERO
[141月2024 04:55:16.164] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Blend gbuffers_water.colortex0=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ZERO
[141月2024 04:55:16.164] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Blend gbuffers_weather.colortex0=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ZERO
[141月2024 04:55:16.164] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Blend gbuffers_hand_water.colortex0=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ZERO
[141月2024 04:55:16.164] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Blend gbuffers_textured.colortex0=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ZERO
[141月2024 04:55:16.164] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] Invalid program name: gbuffers_entities_translucent
[141月2024 04:55:16.164] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] Invalid program name: gbuffers_block_translucent
[141月2024 04:55:16.164] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] Invalid program name: gbuffers_particles_translucent
[141月2024 04:55:16.165] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Fixed size colortex4: 192 108
[141月2024 04:55:16.336] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Noise texture enabled
[141月2024 04:55:16.336] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Noise texture resolution: 512
[141月2024 04:55:16.336] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] shadowHardwareFiltering1
[141月2024 04:55:16.336] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Shadow map resolution: 4096
[141月2024 04:55:16.336] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Shadow map distance: 192.0
[141月2024 04:55:16.337] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Shadow distance render mul: 1.0
[141月2024 04:55:16.337] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Shadow map interval size: 2.0
[141月2024 04:55:16.337] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Sun path rotation: -35.0
[141月2024 04:55:16.337] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Dryness halflife: 300.0
[141月2024 04:55:16.337] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Wetness halflife: 70.0
[141月2024 04:55:16.365] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Program loaded: world0/shadow
[141月2024 04:55:16.367] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Program disabled: world0/shadowcomp
[141月2024 04:55:16.370] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Program disabled: world0/prepare
[141月2024 04:55:16.478] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Noise texture enabled
[141月2024 04:55:16.479] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Noise texture resolution: 512
[141月2024 04:55:16.479] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] shadowHardwareFiltering1
[141月2024 04:55:16.479] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Shadow map resolution: 4096
[141月2024 04:55:16.479] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Shadow map distance: 192.0
[141月2024 04:55:16.479] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Shadow distance render mul: 1.0
[141月2024 04:55:16.479] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Shadow map interval size: 2.0
[141月2024 04:55:16.479] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Sun path rotation: -35.0
[141月2024 04:55:16.479] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Dryness halflife: 300.0
[141月2024 04:55:16.479] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Wetness halflife: 70.0
[141月2024 04:55:16.500] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Program loaded: world0/gbuffers_basic
[141月2024 04:55:16.500] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Blend buffer: 0
[141月2024 04:55:16.554] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] Error compiling vertex shader: /shaders/world0/gbuffers_line.vsh
[141月2024 04:55:16.554] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] File: 1 = /shaders/program/gbuffer/basic.glsl
[141月2024 04:55:16.554] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] File: 2 = /shaders/include/global.glsl
[141月2024 04:55:16.554] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] File: 3 = /shaders/settings.glsl
[141月2024 04:55:16.554] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] File: 4 = /shaders/include/utility/color.glsl
[141月2024 04:55:16.554] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] File: 5 = /shaders/include/utility/encoding.glsl
[141月2024 04:55:16.554] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Shader info log: /shaders/world0/gbuffers_line.vsh
ERROR: 1:32: 'preprocessor evaluation' : bad expression 
ERROR: 1:32: '#if' : unexpected tokens following directive 
ERROR: 1:32: '' : missing #endif 
ERROR: 3 compilation errors.  No code generated.
[141月2024 04:55:16.609] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Noise texture enabled
[141月2024 04:55:16.609] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Noise texture resolution: 512
[141月2024 04:55:16.609] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] shadowHardwareFiltering1
[141月2024 04:55:16.609] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Shadow map resolution: 4096
[141月2024 04:55:16.609] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Shadow map distance: 192.0
[141月2024 04:55:16.609] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Shadow distance render mul: 1.0
[141月2024 04:55:16.609] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Shadow map interval size: 2.0
[141月2024 04:55:16.609] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Sun path rotation: -35.0
[141月2024 04:55:16.609] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Dryness halflife: 300.0
[141月2024 04:55:16.609] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Wetness halflife: 70.0
[141月2024 04:55:16.629] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] Error linking program: 17 (gbuffers_line)
[141月2024 04:55:16.629] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Program info log: gbuffers_line
Program Link Failed for unknown reason.
[141月2024 04:55:16.629] [Render thread/ERROR] [com.mojang.blaze3d.platform.GlDebug/]: OpenGL API ERROR: 1000 (glUseProgram has generated an error (GL_INVALID_OPERATION))
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL20C.glUseProgram(Native Method) ~[lwjgl-opengl-3.3.1.jar%23147!/:build 7]
	at org.lwjgl.opengl.GL20.glUseProgram(GL20.java:398) ~[lwjgl-opengl-3.3.1.jar%23147!/:build 7]
	at com.mojang.blaze3d.platform.GlStateManager._glUseProgram(GlStateManager.java:402) ~[client-1.20.1-20230612.114412-srg.jar%23180!/:?]
	at net.optifine.shaders.Shaders.useProgram(Shaders.java:4040) ~[OptiFine_1.20.1_HD_U_I6.jar%23191!/:?]
	at net.optifine.shaders.Shaders.setupProgram(Shaders.java:3071) ~[OptiFine_1.20.1_HD_U_I6.jar%23191!/:?]
	at net.optifine.shaders.Shaders.init(Shaders.java:2595) ~[OptiFine_1.20.1_HD_U_I6.jar%23191!/:?]
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4823) ~[OptiFine_1.20.1_HD_U_I6.jar%23191!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1584) ~[client-1.20.1-20230612.114412-srg.jar%23180!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1279) ~[client-1.20.1-20230612.114412-srg.jar%23180!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23180!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23180!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.85.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.1.47.jar:47.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
[141月2024 04:55:16.630] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] OpenGL Error: 1000 (glUseProgram has generated an error (GL_INVALID_OPERATION))
[141月2024 04:55:16.630] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_line, at: useProgram
[141月2024 04:55:16.630] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] OpenGL Error: 1282 (Invalid operation)
[141月2024 04:55:16.631] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Program info log: gbuffers_line
Program Link Failed for unknown reason.
[141月2024 04:55:16.631] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] [Shaders] Error: Invalid program "gbuffers_line"
[141月2024 04:55:16.631] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] [Shaders] Error: Invalid program "gbuffers_line"
```

**Comment by OKHI233** [comment]
Closing as I don't use OptiFine above 1.16.5 anymore, and 1.16.5 does not have this problem either.
